public enum CheckboxDataSource
{
	MouseInvert = 0,
	Vsync = 1,
	Aniso = 2,
	Fullscreen = 3,
	SMAA = 4,
	SSAO = 5,
	GamepadInvert = 6,
	MouseSmoothing = 7,
	AudioDiaries = 8,
	TrainingMessages = 9,
	UseMap = 10,
	Headbob = 11,
	Subtitles = 12,
	UnlockDoors = 13,
	LightsOn = 14,
	MotionBlur = 15,
	Bloom = 16,
	DisableReticule = 17,
	DisableFrobHighlight = 18,
	DisableFrobText = 19,
	AimAssist = 20,
	StickSwap = 21,
	OverlayText = 22,
	MouseAcceleration = 23,
	CommentaryMode = 24,
}
