using UnityEngine;

public class vp_FPSCamera : vp_Component
{
	public Camera ExtraCamera;
	public Vector2 MouseSensitivity;
	public int MouseSmoothSteps;
	public float MouseSmoothWeight;
	public bool SmoothMouse;
	public bool MouseAcceleration;
	public float MouseAccelerationThreshold;
	public bool MouseAccelerationOption;
	public bool MouseInverted;
	public bool GamepadInverted;
	public Vector2 GamepadSensitivity;
	public bool UseGamepadInput;
	public bool SmoothGamepad;
	public float GamepadSmoothWeight;
	public bool UseGamepadEaseCurve;
	public AnimationCurve GamepadEaseCurve;
	public bool AimAssistActive;
	public Vector2 GamepadAimAssistSensitivity;
	public Vector2 MouseAimAssistSensitivity;
	public float GamepadSensitivityScalar;
	public float MouseSensitivityScalar;
	public float RenderingFieldOfView;
	public float RenderingZoomDamping;
	public Vector3 PositionOffset;
	public float PositionGroundLimit;
	public float PositionSpringStiffness;
	public float PositionSpringDamping;
	public float PositionSpring2Stiffness;
	public float PositionSpring2Damping;
	public float PositionKneeling;
	public Vector2 RotationPitchLimit;
	public Vector2 RotationYawLimit;
	public float RotationSpringStiffness;
	public float RotationSpringDamping;
	public float RotationKneeling;
	public float RotationStrafeRoll;
	public float RotationThreshold;
	public float RotationSoundInterval;
	public float ShakeSpeed;
	public Vector3 ShakeAmplitude;
	public Vector4 BobRate;
	public Vector4 BobAmplitude;
	public float BobInputVelocityScale;
	public float BobMaxInputVelocity;
	public float BobStepThreshold;
	public bool Headbob;
	public bool m_bUseBumpSmoothing;
	public float m_fMaxBumpSmoothingHeightDelta;
	public Vector2 m_fSmoothingDecayDistances;
	public Vector2 m_fSmoothingDecayRates;
}
